export const TEXTS = {
  GAME_PANEL_REST: 'Odpocznij',
  GAME_PANEL_REST_END: 'Koniec',
  GAME_PANEL_PLAY: 'Graj',
  EFFECT_DISPLAY_DIALOG_TITLE: 'Efekt',
  EFFECT_DISPLAY_NEXT_ENCOUNTER: 'Następne wyzwanie',
  EFFECT_DISPLAY_BACK_TO_PANEL: 'Wróć do panelu',
  EQUIPMENT_NO_ITEMS: 'Brak przedmiotów',
  FIGHT_ENEMY_DESCRIPTION: 'Opis przeciwnika',
  FIGHT_ENEMY_BUTTON: 'Walcz',
  GET_REST_TITLE: 'Jesteś zmęczony',
  GET_REST_TEXT: 'Twoje punkt życia lub energii są niewystarczające',
  GET_REST_BUTTON_LABEL: 'Odpocznij',
  ITEMS_SLOTS_HEAD: 'Głowa',
  ITEMS_SLOTS_CHEST: 'Klatka',
  ITEMS_SLOTS_ARMS: 'Ręce',
  ITEMS_SLOTS_LEGS: 'Nogi',
  ITEMS_SLOTS_WEAPON: 'Broń',
  PC_LEVEL: 'Poziom',
  PC_CLASS: 'Klasa',
  ROUNDS_DAMAGE: 'Obrażenia',
  ROUNDS_WINNER: 'Zwycięsca',
  ROUNDS_NEXT: 'Następne',
  EFFECT: 'Efekt',
  LEVEL_UP: 'Nowy poziom',
  LEVEL_UP_DESCRIPTION: 'Udało Ci się osiągnąć nowy poziom!',
  ROUNDS_RESULTS: 'Wyniki',
  ROUNDS_SKIP: 'Pomiń',
};
