export const TEXTS = {
  CONNECT_ERROR: 'Błąd połączenia z portfelem kryptowalut',
  AUTOCONNECT_ERROR: 'Błąd automatycznego połączenia z portfelem kryptowalut',
  DISCONNECT_ERROR: 'Błąd rozłączenia z portfelem kryptowalut',
  GET_OWNED_ITEMS_ERROR: 'Błąd pobrania posiadanych przedmiotów',
  GET_STARTING_WEAPONS_ERROR: 'Błąd pobierania broni startowych',
  GET_STARTING_WEAPON_ERROR: 'Błąd pobierania broni startowej',
  CLAIM_STARTING_WEAPON_ERROR: 'Błąd odbierania broni startowej',
  GET_LISTINGS_ERROR: 'Błąd pobrania listingu przedmiotów',
  CREATE_LISTING_SUCCESS: 'Przedmiot został wystawiony na sprzedaż',
  CREATE_LISTING_ERROR: 'Błąd dodowania listingu przedmiotu',
  BUY_FROM_LISTING_SUCCESS: 'Udało się kupić przedmiot',
  BUY_FROM_LISTING_ERROR: 'Błąd kupowania listingu przedmiotu',
  ADD_NEW_ITEM_SUCCESS: 'Udało się dodać nowy przedmiot',
  ADD_NEW_ITEM_ERROR: 'Błąd dodawania nowego przedmiotu',
  SET_CONDITIONS_SUCCESS: 'Udało się ustawić warunki pozyskiwania NFT',
  SET_CONDITIONS_ERROR: 'Błąd ustawiania warunków dla pozyskania NFT',
  UPLOAD_IMAGE_ERROR: 'Błąd wgrywania zdjęcia',
  GET_ITEMS_ERROR: 'Błąd pobierania przedmiotów',
  GET_ITEM_ERROR: 'Błąd pobierania przedmiotu',
  UPDATE_ITEM_ERROR: 'Błąd aktualizacji przedmiotu',
  UPDATE_ITEM_SUCCESS: 'Udało się zakutalizować przedmiot',
  GET_CLAIM_CONDITION_MAX_CLAIMABLE_SUPPLY:
    'Błąd pobierania warunku pozyskania NFT',
  UPDATE_CLAIM_CONDITION: 'Błąd aktualizacji warunku pozyskania NFT',
  LOOTBOX: 'Skrzynia',
  LOOTBOX_DESCRIPTION: 'Skrzynia z losowym przedmiotem',
  GET_LOOTBOXES_LISTINGS_ERROR: 'Błąd pobierania dostępnych skrzyń',
  GET_OWNED_LOOTBOXES_ERROR: 'Błąd pobierania posiadanych skrzyń',
  BUY_LOOTBOX_ERROR: 'Błąd kupowania skrzyni',
  ADD_TO_PACK_ERROR: 'Błąd dodawania przedmiotów do puli',
  CLAIM_ITEM_ERROR: 'Błąd pozyskiwania przedmiotu',
  OPEN_PACK_ERROR: 'Błąd otwierania skrzyni',
  ADD_NEW_PACK_ERROR: 'Błąd dodawania nowej skrzyni',
  CREATE_PACK_LISTING_ERROR: 'Błąd wystawiania skrzyni na sprzedaż',
  CLAIM_GEARION_ERROR: 'Błąd pozyskiwania monet',
  CONNECTION_REJECTED: 'Połączenie zostało odrzucone',
  ACCEPT_CONNECTION: 'Zajrzyj do swojego portfela i zaakceptuj połączenie',
  INTERNAL_METAMASK: 'Błąd wewnętrzny Metamask. Spróbuj ponownie później',
  CANNOT_CONNECT: 'Nie można nawiązać połączenia',
  APPROVING_ERROR: 'Nie można zaakceptować wystawiania przedmiotu na sprzedaż',
  CREATE_PACK_LISTING_SUCCESS:
    'Udało się utworzyć i wystawić paczkę na sprzedaż',
};
